Repository ixi-U/ixi-U-fe, pull requests merged in 2025-06, with the labels that each got.

#4 [feat]:[SCRUM 14] 요금제 목록 조회 기능
  package-lock.json
  package.json
  src/App.js
  src/api/planApi.js
  src/assets/ixi-u.png
  src/components/PlanCard.css
  src/components/PlanCard.jsx
  src/components/PlanListPage.css
  src/components/PlanListPage.jsx
  src/components/SortDropdown.css
  src/components/SortDropdown.jsx
  src/constants/planOptions.js
  src/styles/global.css
Labels: feat

#6 [feat]:[SCRUM-16] 요금제 별 리뷰 확인 기능
  package-lock.json
  src/App.js
  src/api/planReviewApi.js
  src/components/PlanCard.jsx
  src/pages/PlanDetailPage.css
  src/pages/PlanDetailPage.jsx
Labels: feat

#7 [feat]:[SCRUM-57] 요금 상세 정보 조회 페이지 개발
  src/App.js
  src/components/PlanDetailPage.css
  src/components/PlanDetailPage.jsx
  src/pages/PlanDetailPage.css
  src/pages/PlanDetailPage.jsx
Labels: feat

#14 [fix]:[SCRUM-30] env 파일 삭제
  .env.development
  .env.production
Labels: chore

#16 [feat]:[SCRUM-58] 마이페이지 화면 구성
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/api/planApi.js
  src/api/userApi.js
  src/components/ChatbotButton.css
  src/components/ChatbotButton.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/components/InfoCard.css
  src/components/InfoCard.jsx
  src/components/PlanHistoryItem.css
  src/components/PlanHistoryItem.jsx
  src/components/PlanHistoryList.css
  src/components/PlanHistoryList.jsx
  src/components/Sidebar.css
  src/components/Sidebar.jsx
  src/pages/MainPage.js
  src/pages/MyPage.css
  src/pages/MyPage.jsx
Labels: feat

#18 [feat]:[SCRUM-65] 어드민 요금제 등록 ui 및 api 연동, 요금제 삭제 ui 구현
  .gitignore
  src/App.js
  src/api/auth.js
  src/api/planApi.js
  src/assets/ixi-u.png
  src/assets/ixi-u2.png
  src/assets/kakao-login.png
  src/components/header/Header.jsx
  src/pages/Main.css
  src/pages/MainPage.jsx
  src/pages/admin/AdminLayout.css
  src/pages/admin/AdminLayout.jsx
  src/pages/admin/DeletePlan.css
  src/pages/admin/DeletePlanPage.jsx
  src/pages/admin/RegisterPlan.css
  src/pages/admin/RegisterPlanPage.jsx
  src/pages/login/KakaoRedirectHandler.js
  src/pages/login/LoginStatus.jsx
  src/pages/plans/plan-list/PlanListPage.jsx
  src/utils/jwtUtils.js
Labels: feat, fix

#20 [feat]:[SCRUM-82] 챗봇 메시지 공백 처리 로직 추가
  src/pages/chatbot/ChatBotPage.jsx
Labels: fix

#21 [fix]:[SCRUM-93] 잘못된 서버 URL 환경 변수 참조 수정
  src/api/planApi.js
  src/api/planDetail.js
  src/api/planReviewApi.js
  src/api/userApi.js
  src/pages/admin/BundledBenefitRegisterForm.jsx
  src/pages/admin/SingleBenefitRegisterForm.jsx
  src/pages/chatbot/ChatBotPage.jsx
  src/pages/login/Logout.jsx
Labels: fix

#23 [feat]:[SCRUM-95] 챗봇 추천 API 연동
  src/pages/chatbot/ChatBotPage.jsx
Labels: feat

#24 [feat]:[SCRUM-95] 챗봇 추천 API 예외 제거
  src/pages/chatbot/ChatBotPage.jsx
Labels: feat

#25 [feat]:[SCRUM-95] 챗봇 welcome 메시지 띄어쓰기
  src/pages/chatbot/ChatBotPage.jsx
Labels: feat

#26 [fix]:[SCRUM-99] 요금제 목록 조회 뷰 수정
  public/index.html
  public/ixi-u.ico
  public/ixi-u2.ico
  src/pages/MainPage.js
  src/pages/chatbot/ChatBotPage.css
  src/pages/chatbot/ChatBotPage.jsx
  src/pages/plans/plan-list/PlanCard.jsx
  src/pages/plans/plan-list/PlanListPage.jsx
Labels: fix

#29 [fix]:[SCRUM-106] 마이페이지 요금제 등록과 로그아웃 에러 수정
  src/components/header/Header.jsx
  src/pages/user/MyPage.jsx
Labels: fix

#30 [fix]:[SCRUM-107] 마이페이지에서 혜택들이 Object로 뜨던 오류 수정
  src/pages/user/MyPage.jsx
Labels: fix

#31 [feat]:[SCRUM-108] 로그인 상태와 연관된 UI 수정
  src/App.js
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/pages/admin/AdminLayout.css
  src/pages/admin/AdminLayout.jsx
  src/pages/admin/AdminPage.jsx
  src/pages/admin/AdminSidebar.jsx
  src/pages/admin/DeletePlanPage.jsx
  src/pages/admin/RegisterPlan.css
  src/pages/admin/RegisterPlanPage.jsx
  src/pages/chatbot/ChatBotPage.jsx
  src/pages/chatbot/ChatbotButton.css
  src/pages/chatbot/ChatbotButton.jsx
  src/pages/login/SocialLogin.jsx
  src/pages/plans/plan-list/PlanListPage.css
  src/pages/plans/plan-list/PlanListPage.jsx
  src/pages/user/MyPage.css
  src/pages/user/MyPage.jsx
  src/pages/user/Sidebar.css
Labels: feat

#32 [fix]:[SCRUM-115] 마이페이지 수정 및 요금제 목록 에러 수정
  src/assets/styles/global.css
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/header/Header.css
  src/pages/admin/AdminLayout.css
  src/pages/admin/AdminPage.jsx
  src/pages/plans/plan-list/PlanListPage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/PlanHistoryItem.css
  src/pages/user/PlanHistoryItem.jsx
  src/pages/user/PlanHistoryList.jsx
Labels: fix

#35 [feat]:[SCRUM-112] 요금제 개수 조회 화면 개발
  src/api/planApi.js
  src/pages/login/KakaoRedirectHandler.js
  src/pages/plans/plan-list/PlanListPage.jsx
Labels: feat

#36 [refactor]:[SCRUM-117] UI 전면 리디자인
  public/index.html
  src/App.js
  src/components/footer/Footer.css
  src/components/footer/Footer.jsx
  src/constants/planOptions.js
  src/pages/Main.css
  src/pages/admin/AdminLayout.css
  src/pages/admin/DeletePlan.css
  src/pages/admin/RegisterPlan.css
  src/pages/admin/SingleBenefitRegisterForm.css
  src/pages/chatbot/ChatBotPage.css
  src/pages/chatbot/ChatBotPage.jsx
  src/pages/login/Logout.jsx
  src/pages/login/OnBoarding.jsx
  src/pages/login/Onboarding.css
  src/pages/login/SocialLogin.jsx
  src/pages/plans/plan-detail/PlanDetailPage.css
  src/pages/plans/plan-detail/PlanDetailPage.jsx
  src/pages/plans/plan-detail/ReviewModal.css
  src/pages/user/InfoCard.css
  src/pages/user/MyPage.css
  src/pages/user/MyPage.jsx
  src/pages/user/PlanHistoryItem.css
  src/pages/user/PlanHistoryList.css
  src/pages/user/Sidebar.css
Labels: refactor

#38 [fix]:[SCRUM-124] 신고된 리뷰 조회 페이지 추가 및 마이페이지 버그 수정
  src/pages/admin/AdminPage.jsx
  src/pages/admin/AdminSidebar.jsx
  src/pages/admin/ReportedReviewsPage.jsx
  src/pages/user/MyPage.jsx
Labels: feat, fix

#39 [feat]:[SCRUM-122] 요금제 목록 필드값 처리 로직 추가
  src/pages/plans/plan-list/PlanCard.jsx
  src/pages/plans/plan-list/PlanListPage.jsx
Labels: feat

#40 [feat]:[SCRUM-125] 요금제 상세 - 묶음 혜택 UI 수정
  src/pages/plans/plan-detail/PlanDetailPage.css
  src/pages/plans/plan-detail/PlanDetailPage.jsx
  src/pages/plans/plan-list/PlanCard.jsx
Labels: feat

#41 [feat]:[SCRUM-126] Sticky Footer 문제 수정
  src/App.js
  src/assets/styles/layout.css
  src/components/footer/Footer.css
  src/pages/user/MyPage.jsx
  src/pages/user/Sidebar.jsx
Labels: feat, fix

#42 [feat]:[SCRUM-136] 요금제 비활성화/활성화 페이지 UI 수정
  src/pages/admin/AdminPage.jsx
  src/pages/admin/AdminSidebar.jsx
  src/pages/admin/DeletePlan.css
  src/pages/admin/DeletePlanPage.jsx
Labels: feat

#44 [feat]:[SCRUM-141] 요금제 최종 UI 수정
  src/assets/styles/global.css
  src/pages/admin/DeletePlan.css
  src/pages/admin/DeletePlanPage.jsx
  src/pages/admin/RegisterPlanPage.jsx
  src/pages/plans/plan-detail/PlanDetailPage.jsx
  src/pages/plans/plan-list/PlanCard.css
  src/pages/plans/plan-list/PlanCard.jsx
  src/pages/plans/plan-list/PlanListPage.css
  src/pages/plans/plan-list/PlanListPage.jsx
Labels: feat, fix
